# Generated by Django 5.1.1 on 2024-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="poster_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
